name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup docker-compose.yml from secret
      run: |
        printf '%s\n' "$DOCKER_COMPOSE_YML" > docker-compose.yml
      env:
        DOCKER_COMPOSE_YML: ${{ secrets.DOCKER_COMPOSE_YML }}

    - name: Check docker-compose.yml file
      run: cat docker-compose.yml

    - name: Build Docker image
      run: docker build -t frontend-app .

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/satellite_assembly/satellite_assembler/space_vpx_satellite_frontend
          git reset --hard HEAD
          git pull origin main
          git pull
          docker compose down
          docker compose up -d --build

    - name: Health check
      run: curl --fail http://158.160.187.238:80 || exit 1
