name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Setup docker-compose.yml from secret
      run: |
        printf '%s\n' "$DOCKER_COMPOSE_YML" > docker-compose.yml
      env:
        DOCKER_COMPOSE_YML: ${{ secrets.DOCKER_COMPOSE_YML }}

    - name: Check docker-compose.yml file
      run: cat docker-compose.yml

    - name: Build Docker image
      run: docker build -t frontend-app .

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/frontend
          git pull
          docker compose down
          docker compose up -d --build

    - name: Health check
      run: curl --fail http://localhost:80 || exit 1
